DEFAULT_CONNECTION = "/dev/ttyACM0"
DEFAULT_BAUD = 115200

BATTERY_MIN_VOLTAGE = 21.0
BATTERY_CRITICAL_VOLTAGE = 20.0

MIN_GPS_SATELLITES = 8
MIN_GPS_FIX_TYPE = 3
GPS_HDOP_WARNING = 1.5
GPS_HDOP_CRITICAL = 2.5

VIBRATION_WARNING_RMS = 3.0
VIBRATION_CRITICAL_RMS = 6.0

VIBE_WARNING = 30.0
VIBE_CRITICAL = 60.0
CLIPPING_WARNING = 1

CPU_TEMP_WARNING_C = 70
CPU_TEMP_CRITICAL_C = 80
CPU_USAGE_WARNING_PERCENT = 85
RAM_USAGE_WARNING_PERCENT = 85

LOG_INTERVAL_SECONDS = 0.2
STATUS_PRINT_INTERVAL_SECONDS = 1.0
